### PR TITLE
Run tests against all lower versions

### PR DESCRIPTION
**Pull request by mnapoli**
Currently Travis runs tests against Symfony 2.8 (lower bound) and 3.0 (upper bound). With this change tests will run against the latest versions (default) and also against all lowest versions of the dependencies (so not just Symfony). I hope it all works fine ;)

### CODE REVIEW

**Comment by mnapoli** [comment]
😞  I think the build needs to be restarted manually because the error is "Could not authenticate against github.com"

**Comment by sroze** [comment]
It looks like there are some issues here that sounds to be PhpSpec issues, maybe the lower version is not the good one... :(

**Comment by mnapoli** [comment]
Right. I've tried to update phpspec we'll see how it goes, I'll try other packages if it's not enough. When I add tests with "lowest dependencies" I always find errors like that so I'm not surprised.

**Comment by sroze** [comment]
And that's prefect now. Thank you @mnapoli!

**Pull request merged**
