### PR TITLE
Remove useless deps

### PR DESCRIPTION
**Pull request by tyx**
I don't find any usage of these 3 libraries in fact...

I'm missing something ?

Tests still green...

### CODE REVIEW

**Comment by sroze** [comment]
ouuups, didn't see this PR.. that's the trick with monolith repositories, is that these dependencies are dependencies of a few bits around 😉 

Shouldn't we move them to `suggest` ?

**Comment by tyx** [comment]
Np :+1: 

Tolerance looks to work completely without so I don't see the need to add them as suggestion. We definitively not need them :D 

(I rebased the PR anyway)

**Comment by sroze** [comment]
Let's go for it then!

**Comment by sroze** [comment]
Thanks @tyx !

**Pull request merged**
